### ISSUE TITLE
Unable to assign QObject* to void

### ISSUE THREAD

**Issue by belogermanotta** [SamVerschueren/beRail#1]
Hi Sam,

I follow your example and got this error when set service to viewmodel
service: registerService

I'm already Registertype
qmlRegisterType<RegisterService>("foo.bar.services", 1, 0, "RegisterService");

attachedObjects: [
        RegisterService {
            id: registerService
        },
        RegisterViewModel {
            id: registerViewModel
            service: registerService
        }
]

please help

**Comment by SamVerschueren** [comment]
Hi

So I guess you made a Q_PROPERTY for injecting your service? Have you added this line of code?

``` C++
qRegisterMetaType<QObject*>("RegisterService*");
```

You can find that line in BeRail.cpp

**Comment by belogermanotta** [comment]
Thank you Sam!
It works.

but in BeRail.cpp why you only use qRegisterMetaType for model?

**Comment by SamVerschueren** [comment]
Valid point you have there :).

Have you imported foo.bar.services 1.0 in your QML? If not, try to do that and remove the qRegisterMetaType line.

**Comment by belogermanotta** [comment]
Hi Sam,
I'm already imported it. I don't know why it doesn't work.

in another case I want set ListView and have same result , should I still use qRegisterMetaType?
